### ISSUE TITLE
allow to read gitlab-token from per-machine config file

### ISSUE THREAD

**Issue by benedikt-bartscher** [bjd2385/gitlabci-lint-pre-commit-hook#12]
i dont want to add my gitlab token to my whole shell env for security reasons. Also i dont want to set this env manually. What about implementing a config file where we can store this token?

**Comment by bjd2385** [comment]
@benedikt-bartscher Sure, I'm down to add a few different ways of configuring this. Maybe there could be a default config location it looks, such as `~/.gitlab-ci/config.yaml`? Or are you looking for more of a dotenv-type lookup. 

I just want to be sure a config file with a secret doesn't accidentally get checked into git.

**Comment by benedikt-bartscher** [comment]
Thanks for your reply. A default config location would be nice, but i prefer keeping stuff like this in `~/.config/` like so: `~/.config/gitlabci-lint/config.yaml`.  But that's your choice!

**Comment by bjd2385** [comment]
Ah, I like that better! Standard location makes for easier debugging / setup for new users.

**Comment by bjd2385** [comment]
Solved by #15. Let me know if you experience any problems with reading values from config files!
