### ISSUE TITLE
improve GITLAB_TOKEN env var

### ISSUE THREAD

**Issue by benedikt-bartscher** [bjd2385/gitlabci-lint-pre-commit-hook#13]
sometimes its a good security practise to use different tokens for different things. It would be awesome if gitlabci-lint-pre-commit-hook would first try to read the token from GITLABCI_LINT_TOKEN and then fallback to GITLAB_TOKEN

**Comment by bjd2385** [comment]
Absolutely this logic could be added.

**Comment by bjd2385** [comment]
@benedikt-bartscher should be fixed by #14 in v1.1.6. Will work on your other request next

**Comment by bjd2385** [comment]
I made improvements to this feature since I had a little time this 3 day weekend in #15
